----------DROPS----------
--DROPS TABLES
DROP TABLE ACHAT_BILLET;
DROP TABLE SEANCE;
DROP TABLE ACTEUR_FILM;
DROP TABLE FILM;
DROP TABLE CINEMA;
DROP TABLE ACTEUR;
DROP TABLE TJOB;
DROP TABLE TJOB_EXEC_HISTO;
--DROP TABLE TJOB_LOGS;
DROP TABLE TERRORS;

--DROPS SEQUENCES
DROP SEQUENCE ACHAT_BILLET_SEC;
DROP SEQUENCE TJOB_SEC;
DROP SEQUENCE TERROR_SEC;
DROP SEQUENCE SEANCE_SEC;
DROP SEQUENCE ACTEUR_FILM_SEC;
DROP SEQUENCE FILM_SEC;
DROP SEQUENCE CINEMA_SEC;
DROP SEQUENCE ACTEUR_SEC;
DROP SEQUENCE TJOB_EXEC_HISTO_SEC;
DROP SEQUENCE TJOB_LOGS_SEC;

-- DROPS TRIGGERS
--DROP TRIGGER ACTEUR_ON_INSERT;
--DROP TRIGGER TJOB_ON_INSERT;
--DROP TRIGGER TJOBEXEC_HISTO_ON_INSERT;
--DROP TRIGGER TJOB_LOGS_ON_INSERT;
--DROP TRIGGER TERROR_ON_INSERT;
--DROP TRIGGER CINEMA_ON_INSERT;
--DROP TRIGGER FILM_ON_INSERT;
--DROP TRIGGER ACTEUR_FILM_ON_INSERT;
--DROP TRIGGER SEANCE_ON_INSERT;
--DROP TRIGGER ACHAT_BILLET_ON_INSERT;
--DROP TRIGGER CREATE_TABLE_TRIGGER;
--DROP TRIGGER DELETE_TABLE_TRIGGER;

-- DROPS PACKAGE
DROP PACKAGE PACKAGE1;