----------INSERTION DONNEE----------
-- Acteur
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Leavitt',
        'Robin',
        TO_DATE('19701130', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Jacquet',
        'Fabien',
        TO_DATE('19900705', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Ancel',
        'Pascal',
        TO_DATE('19751025', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Azais',
        'Capucine',
        TO_DATE('19910430', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Chagnon',
        'Fanny',
        TO_DATE('19880114', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Girault',
        'Rosalie',
        TO_DATE('19730926', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Bridges',
        'Jeff',
        TO_DATE('19751025', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Wilde',
        'Olivia',
        TO_DATE('19910430', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Hedlund',
        'Garrett',
        TO_DATE('19880114', 'YYYY-MM-DD'));
INSERT INTO ACTEUR(NOM, PRENOM, DATE_NAISSANCE)
VALUES ('Sheen',
        'Michael',
        TO_DATE('19730926', 'YYYY-MM-DD'));
-- Film
INSERT INTO FILM(NOM, DUREE)
VALUES ('dortoir de midi', 110);
INSERT INTO FILM(NOM, DUREE)
VALUES ('La patience de la peur', 123);
INSERT INTO FILM(NOM, DUREE)
VALUES ('Protocole des magiciens', 94);
INSERT INTO FILM(NOM, DUREE)
VALUES ('La charite des multiples', 115);
INSERT INTO FILM(NOM, DUREE)
VALUES ('Virus de la revolution', 107);
INSERT INTO FILM(NOM, DUREE)
VALUES ('La science des infideles', 75);
-- Acteur_Film
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (1, 4);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (2, 6);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (3, 5);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (4, 2);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (5, 3);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (6, 1);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (3, 9);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (2, 8);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (4, 7);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (1, 6);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (5, 2);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (6, 10);
INSERT INTO ACTEUR_FILM(ID_FILM, ID_ACTEUR)
VALUES (3, 10);
-- Cinema
INSERT INTO CINEMA(NOM, ADRESSE, CP, VILLE, NB_SALLES)
VALUES ('Cine Planete',
        '14 place Jean Jaures',
        '26100',
        'Romans-Sur-Isere',
        8);
INSERT INTO CINEMA(NOM, ADRESSE, CP, VILLE, NB_SALLES)
VALUES ('Cine Lumiere',
        '5 rue du President Felix Faure',
        '26100',
        'Romans-Sur-Isere',
        3);
INSERT INTO CINEMA(NOM, ADRESSE, CP, VILLE, NB_SALLES)
VALUES ('La Nef',
        '18 bd Edouard Rey',
        '38000',
        'Grenoble',
        5);
INSERT INTO CINEMA(NOM, ADRESSE, CP, VILLE, NB_SALLES)
VALUES ('Cinema Juliet Berto',
        'Passage du Palais de Justice',
        '38000',
        'Grenoble',
        4);
INSERT INTO CINEMA(NOM, ADRESSE, CP, VILLE, NB_SALLES)
VALUES ('Gaumont Alesiao',
        '73 av. du Gal-Leclerc',
        '75014',
        'Paris',
        8);
INSERT INTO CINEMA(NOM, ADRESSE, CP, VILLE, NB_SALLES)
VALUES ('Pathe La Villette',
        '30 avenue Corentin Cariou',
        '75019',
        'Paris',
        7);
-- Seance
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191124', 'YYYY-MM-DD'), 1, 5);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191004', 'YYYY-MM-DD'), 2, 1);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20190912', 'YYYY-MM-DD'), 3, 6);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20190821', 'YYYY-MM-DD'), 4, 4);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191108', 'YYYY-MM-DD'), 5, 2);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191117', 'YYYY-MM-DD'), 6, 3);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191224', 'YYYY-MM-DD'), 5, 4);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20190813', 'YYYY-MM-DD'), 1, 6);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191115', 'YYYY-MM-DD'), 2, 2);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191007', 'YYYY-MM-DD'), 6, 2);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191117', 'YYYY-MM-DD'), 4, 3);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191022', 'YYYY-MM-DD'), 5, 1);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191101', 'YYYY-MM-DD'), 6, 5);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191117', 'YYYY-MM-DD'), 2, 1);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20190909', 'YYYY-MM-DD'), 1, 1);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191130', 'YYYY-MM-DD'), 5, 3);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20190824', 'YYYY-MM-DD'), 1, 4);
INSERT INTO SEANCE(DATE_SEANCE, ID_CINE, ID_FILM)
VALUES (TO_DATE('20191115', 'YYYY-MM-DD'), 3, 3);
-- Achat_Billets
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191122', 'YYYY-MM-DD'), 9, 1, 0, 1);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191120', 'YYYY-MM-DD'), 7, 1, 1, 5);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191215', 'YYYY-MM-DD'), 9, 2, 0, 4);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191126', 'YYYY-MM-DD'), 9, 1, 0, 2);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191116', 'YYYY-MM-DD'), 7, 4, 1, 6);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191005', 'YYYY-MM-DD'), 7, 4, 1, 6);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191107', 'YYYY-MM-DD'), 9, 1, 0, 9);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191021', 'YYYY-MM-DD'), 9, 3, 0, 18);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191012', 'YYYY-MM-DD'), 7, 1, 0, 15);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191201', 'YYYY-MM-DD'), 9, 2, 0, 7);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191006', 'YYYY-MM-DD'), 7, 2, 0, 8);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191022', 'YYYY-MM-DD'), 9, 1, 1, 16);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191009', 'YYYY-MM-DD'), 9, 2, 0, 3);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20190907', 'YYYY-MM-DD'), 9, 4, 0, 8);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20190913', 'YYYY-MM-DD'), 9, 1, 1, 4);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191211', 'YYYY-MM-DD'), 7, 3, 0, 17);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20190909', 'YYYY-MM-DD'), 7, 3, 0, 17);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20190928', 'YYYY-MM-DD'), 7, 1, 0, 4);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20190914', 'YYYY-MM-DD'), 9, 1, 0, 11);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20190817', 'YYYY-MM-DD'), 7, 2, 1, 14);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191227', 'YYYY-MM-DD'), 9, 1, 0, 13);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191014', 'YYYY-MM-DD'), 7, 4, 0, 10);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191024', 'YYYY-MM-DD'), 7, 4, 0, 3);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20190921', 'YYYY-MM-DD'), 9, 1, 0, 6);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191113', 'YYYY-MM-DD'), 9, 1, 1, 10);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191116', 'YYYY-MM-DD'), 9, 2, 1, 12);
INSERT INTO ACHAT_BILLET(DATE_ACHAT, TARIF, QUANTITE, REDUIT, ID_SEANCE)
VALUES (TO_DATE('20191006', 'YYYY-MM-DD'), 9, 2, 1, 12);