----------SEQUENCES----------
--AUTO INCREMENT SEQUENCE TABLE ACTEUR
CREATE SEQUENCE ACTEUR_SEC;
--AUTO INCREMENT SEQUENCE TABLE TJOB
CREATE SEQUENCE TJOB_SEC;
--AUTO INCREMENT SEQUENCE TABLE TERROR
CREATE SEQUENCE TERROR_SEC;
--AUTO INCREMENT SEQUENCE TABLE CINEMA
CREATE SEQUENCE CINEMA_SEC;
--AUTO INCREMENT SEQUENCE TABLE FILM
CREATE SEQUENCE FILM_SEC;
--AUTO INCREMENT SEQUENCE TABLE ACTEUR_FILM
CREATE SEQUENCE ACTEUR_FILM_SEC;
--AUTO INCREMENT SEQUENCE TABLE SEANCE
CREATE SEQUENCE SEANCE_SEC;
--AUTO INCREMENT SEQUENCE TABLE ACHAT_BILLET
CREATE SEQUENCE ACHAT_BILLET_SEC;
--AUTO INCREMENT SEQUENCE TABLE TJOB_EXEC_HISTO
CREATE SEQUENCE TJOB_EXEC_HISTO_SEC;
--AUTO INCREMENT SEQUENCE TABLE TJOB_LOGS
CREATE SEQUENCE TJOB_LOGS_SEC;