----------TABLES----------
-- TABLE TJOB_LOGS
CREATE TABLE TJOB_LOGS
(
    ID_TJOB_LOGS NUMBER
        CONSTRAINT TJOB_LOGS_PK PRIMARY KEY,
    MESSAGE      varchar(512),
    EXECTIME     TIMESTAMP
);
-- TABLE TJOB
CREATE TABLE TJOB
(
    ID_TJOB               NUMBER
        CONSTRAINT TJOB_PK PRIMARY KEY,
    NOM                   VARCHAR2(50),
    TYPEJOB               CHAR,
    CHEMIN                varchar(100),
    DATEDERNIEREEXECUTION DATE
);
-- TABLE TERRORS
CREATE TABLE TERRORS
(
    ID_TERROR NUMBER
        CONSTRAINT TERRORS_PK PRIMARY KEY,
    ERRORMES     varchar(2048),
    ERRORTIME TIMESTAMP
);
-- TABLE TJOB_EXEC_HISTO
CREATE TABLE TJOB_EXEC_HISTO
(
    ID_TJOB_EXEC_HISTO NUMBER
        CONSTRAINT TJOB_EXEC_HISTO_PK PRIMARY KEY,
    ID_JOB      NUMBER
        CONSTRAINT ID_TJOB_FK references TJOB,
    EXECTIME           TIMESTAMP
);
---------------
--TABLE ACTEUR
CREATE TABLE ACTEUR
(
    ID_ACTEUR      NUMBER
        CONSTRAINT ACTEUR_PK PRIMARY KEY,
    NOM            VARCHAR2(50),
    PRENOM         VARCHAR2(50),
    DATE_NAISSANCE DATE
);
--TABLE CINEMA
CREATE TABLE CINEMA
(
    ID_CINE   NUMBER
        CONSTRAINT CINEMA_PK PRIMARY KEY,
    NOM       VARCHAR2(50),
    ADRESSE   VARCHAR2(50),
    CP        VARCHAR2(5),
    VILLE     VARCHAR2(50),
    NB_SALLES NUMBER
);
--TABLE FILM
CREATE TABLE FILM
(
    ID_FILM NUMBER
        CONSTRAINT FILM_PK PRIMARY KEY,
    NOM     VARCHAR2(50),
    DUREE   NUMBER
);
--TABLE ACTEUR_FILM
CREATE TABLE ACTEUR_FILM
(
    ID_ACTEUR_FILM NUMBER
        CONSTRAINT ACTEUR_FILM_PK PRIMARY KEY,
    ID_FILM        NUMBER
        CONSTRAINT ID_FILM_FK references FILM,
    ID_ACTEUR      NUMBER
        CONSTRAINT ID_ACTEUR_FK references ACTEUR
);
--TABLE SEANCE
CREATE TABLE SEANCE
(
    ID_CINE     NUMBER,
    ID_FILM     NUMBER,
    ID_SEANCE   NUMBER
        CONSTRAINT SEANCE_PK PRIMARY KEY,
    DATE_SEANCE TIMESTAMP
);
--TABLE ACHAT_BILLET
CREATE TABLE ACHAT_BILLET
(
    ID_ACHAT   NUMBER
        CONSTRAINT ACHAT_BILLET_PK PRIMARY KEY,
    DATE_ACHAT TIMESTAMP,
    TARIF      NUMBER,
    QUANTITE   NUMBER,
    REDUIT     CHAR,
    ID_SEANCE  NUMBER
);

----------ALTER----------
--ALTER TABLE ACHAT_BILLET
ALTER TABLE ACHAT_BILLET
    ADD
        CONSTRAINT ACHAT_BILLET_SEANCE_FK FOREIGN KEY (ID_SEANCE) REFERENCES SEANCE;
--ALTER TABLE SEANCE
ALTER TABLE SEANCE
    ADD
        CONSTRAINT SEANCE_CINEMA_FK FOREIGN KEY (ID_CINE) REFERENCES CINEMA (ID_CINE);
ALTER TABLE SEANCE
    ADD
        CONSTRAINT SEANCE_FILM_FK FOREIGN KEY (ID_FILM) REFERENCES FILM (ID_FILM);